Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('',views.index,name='index'),
    path('visual/',views.visual,name='visual'),
    path('visual/like_slide',views.like_slide,name='like_slide'),
    path('visual/refresh_videos',views.refresh_videos,name='refresh_videos'),
    path('quotes/',views.quotes,name='quotes'),
    path('contact/',views.contact,name='contact'),
    path('login_page/',views.login_page,name='login_page'),
]

Quiz/urls.py
from django.urls import path

from . import views

app_name = "Quiz"

urlpatterns = [
    path("quiz",views.quiz_page,name='quiz'),
    path("create-new-quiz",views.createNewQuiz,name='create_new_quiz'),
    path("quiz-page-history",views.QuizHistoryAPIView.as_view(),name='quiz_page_history'),
    path("delete-quiz/",views.deleteQuiz,name='delete_quiz'),
    path("save-question",views.createQuestion,name='add_question'),
    path("preview-quiz/<str:quizId>",views.previewQuiz,name='preview_quiz'),
    path("preview-quiz-json",views.previewQuizJson,name='preview_quiz_json'),
    path("delete-question/",views.deleteQuestion,name='delete_question'),
    path("practice_quiz",views.practice_quiz,name='practice_quiz'),
    path("practice_quiz_json",views.practice_quiz_json,name='practice_quiz_json'),
    
]

User/urls.py
from django.urls import path

from . import views

app_name = "User"

urlpatterns = [
    path("logout",views.logout_user,name='logout'),
    path("login",views.login_user,name='login'),
    path("otp_verification",views.send_otp,name='send_otp'),
    path("verify_otp",views.verify_otp,name='verify_otp'),
    path("reset_password/",views.password_reset,name='reset_password'),
    path("signup",views.signup_user,name='signup'),
    path("profile/<username>",views.view_profile,name='profile'),
    path("edit_profile",views.edit_profile,name='edit_profile'),
    path("edit_password",views.change_password,name='change_password'),
    
]

nirgovind/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls',namespace="Home")),
    path('quiz/',include('Quiz.urls',namespace="Quiz")),
    path('user/',include('User.urls',namespace="User")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import UniqueConstraint

from nirgovind import settings
# Create your models here.

class Slide(models.Model):

    def slides_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'Shloka={instance.chapter}-{instance.shloka}-{instance.slide_number}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    chapter                 = models.PositiveIntegerField(default=0)
    shloka                  = models.PositiveIntegerField(default=0)
    slide_number            = models.PositiveIntegerField(default=0)
    slide_image             = models.ImageField(upload_to=slides_upload_path,null=True,blank=True)

    def __str__(self):
        return f'{self.chapter}.{self.shloka}-{self.slide_number}'
    
    class Meta:
        constraints = [
            UniqueConstraint(fields=['chapter', 'shloka', 'slide_number'], name='unique_slide_number')
        ]

    def clean(self):
        super().clean()
        if Slide.objects.filter(chapter=self.chapter, shloka=self.shloka, slide_number=self.slide_number).exists():
            raise ValidationError('Video number must be unique within each ID.')

class Shloka(models.Model):

    def sanskrit_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'Sanskrit-Shloka={instance.chapter}-{instance.shloka}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    def hindi_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'Hindi-Shloka={instance.chapter}-{instance.shloka}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    def english_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'English-Shloka={instance.chapter}-{instance.shloka}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    def gujarati_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'Gujarati-Shloka={instance.chapter}-{instance.shloka}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    def marathi_upload_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'Marathi-Shloka={instance.chapter}-{instance.shloka}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'slide',new_name)
        return path
    
    chapter                 = models.PositiveIntegerField(default=0)
    shloka                  = models.PositiveIntegerField(default=0)
    sanskrit                = models.ImageField(upload_to=sanskrit_upload_path,null=True,blank=True)
    hindi                   = models.ImageField(upload_to=hindi_upload_path,null=True,blank=True)
    english                 = models.ImageField(upload_to=english_upload_path,null=True,blank=True)
    gujarati                = models.ImageField(upload_to=gujarati_upload_path,null=True,blank=True)
    marathi                 = models.ImageField(upload_to=marathi_upload_path,null=True,blank=True)

    def __str__(self):
        return f'Shloka={self.chapter}-{self.shloka}'


class UserInteraction(models.Model):
    user                    = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_interaction')
    chapter                 = models.PositiveIntegerField(default=0)
    shloka                  = models.PositiveIntegerField(default=0)
    liked                   = models.BooleanField(default=False)

    def __str__(self):
        return f'Shloka={self.chapter}-{self.shloka}{self.liked}'

class YoutubeVideos(models.Model):
    chapter                 = models.PositiveIntegerField(default=0)
    shloka                  = models.PositiveIntegerField(default=0)
    video_id                = models.CharField(max_length=20)
    video_number            = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Shloka={self.chapter}-{self.shloka}{self.video_id}'
    
    class Meta:
        constraints = [
            UniqueConstraint(fields=['chapter', 'shloka', 'video_number'], name='unique_video_number')
        ]

    def clean(self):
        super().clean()
        if YoutubeVideos.objects.filter(chapter=self.chapter, shloka=self.shloka, video_number=self.video_number).exists():
            raise ValidationError('Video number must be unique within each ID.')

Home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core import serializers
from django.conf import settings
import json

from .models import Slide, Shloka, UserInteraction, YoutubeVideos
# Create your views here.
def index(request):
    context = {}
    return render(request,"Home/index.html",context=context)

def visual(request):
    current_ch = 1
    current_sk = 1
    ch_sk = [0,47,72,43,42,29,47,30,28,34,42,55,20,34,27,20,24,28,78]
    if request.method=="POST":
        if request.POST.get('chapter-value'):
            current_ch = int(request.POST.get('chapter-value'))
        if request.POST.get('shloka-value'):
            current_sk = int(request.POST.get('shloka-value'))
    if current_sk>ch_sk[current_ch]:
        current_sk = 1
    slides = Slide.objects.filter(chapter=current_ch,shloka=current_sk).order_by('slide_number')
    current_shloka = Shloka.objects.get(chapter=current_ch,shloka=current_sk)
    likes = UserInteraction.objects.filter(chapter=current_ch,shloka=current_sk,liked=True).count()
    videos = YoutubeVideos.objects.filter(chapter=current_ch,shloka=current_sk).order_by('?')[:4]
    context = {"slides":slides,
               "current_shloka":current_shloka,
               "ch_values":[i+1 for i in range(18)],
               "sk_values":[i+1 for i in range(ch_sk[current_ch])],
               "current_ch":current_ch,
               "current_sk":current_sk,
               "likes":likes,
               "videos":videos,
               "GOOGLE_API_KEY":settings.GOOGLE_API_KEY,
            }
    return render(request,"Home/visual.html",context=context)


@login_required
def like_slide(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        kwargs = {
            'user'    : request.user,
            'chapter' : json_data.get('current_ch'),
            'shloka'  : json_data.get('current_sk'),
        }
        user_interaction, created = UserInteraction.objects.get_or_create(**kwargs)
        user_interaction.liked = json_data.get('liked')
        user_interaction.save()
        return JsonResponse({'message': 'Slide liked successfully'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

def refresh_videos(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        current_ch = json_data.get('current_ch')
        current_sk = json_data.get('current_sk')
        videos = YoutubeVideos.objects.filter(chapter=current_ch,shloka=current_sk).order_by('?')[:3]
        data = serializers.serialize('json', videos)
        return JsonResponse(data, safe=False)
    else:
        return JsonResponse({'error': 'Invalid request method'})

def quotes(request):
    context = {}
    return render(request,"Home/quotes.html",context=context)

def contact(request):
    context = {}
    return render(request,"Home/contact.html",context=context)

def login_page(request):
    context = {}
    return render(request,"Home/login_page.html",context=context)


Home/templates/Home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="description">
    <meta content="" name="keywords">
    
    <link href="{% static 'img/logo.jpg' %}" rel="icon">
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
    <!-- Other-CSS Files -->
    <link href="{% static 'external-css-js/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'external-css-js/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    
    <!-- Main CSS File -->
    <link type="text/css" href="{% static 'style.css' %}" rel="stylesheet">

    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <!-- block for adding css files -->
    {% block css %}
    {% endblock css %}

</head>

<body>
    <div id="body">
        <!-- ======= Header ======= -->
        <header id="header" class="fixed-top ">
          <div class="container d-flex align-items-center">
      
            <a href="{% url 'Home:index' %}" class="logo me-auto"><img src="{% static 'img/logo.jpg' %}" alt="" class="img-fluid"><h3>NIRGOVIND</h3></a>
      
            <nav id="navbar" class="navbar">
              <ul>
                <li><a class="nav-link scrollto active" href="{% url 'Home:index' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'Home:visual' %}">Visual</a></li>
                <li><a class="nav-link scrollto" href="{% url 'Home:quotes' %}">Quotes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'Quiz:quiz' %}">Quiz</a></li>
                <li><a class="nav-link scrollto" href="{% url 'Home:contact' %}">Contact</a></li>
                <li class="dropdown"><a href="#"><span>Reviews</span> <i class="bi bi-chevron-down"></i></a>
                  <ul>
                    <li><a href="#">Comments</a></li>
                    <li><a href="#">Suggestions</a></li>
                  </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="dropdown"><a href="#"><span> {{user.username}} </span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="{% url 'User:profile' user.username %}">Profile</a></li>
                        <li><a href="{% url 'User:logout' %}">Logout</a></li>
                    </ul>
                </li>

                {% else %}
                <li><a class="nav-link scrollto" href="{% url 'User:login' %}">Login</a></li>
                {% endif %}
            
              </ul>
              <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
      
          </div>
        </header><!-- End Header -->

        {% block body %}
        
        {% endblock body %}
      
        <!-- ======= Footer ======= -->
        <footer id="footer">
      
          <div class="footer-top">
            <div class="container">
              <div class="row">
      
                <div class="col-lg-3 col-md-6 footer-contact">
                  <a href="{% url 'Home:index' %}" class="logo me-auto"><img src="{% static 'img/logo.jpg' %}" alt="" class="img-fluid"></a>
                  <h3>NIRGOVIND</h3>
                  <p>
                    Palace Road, Multhan, <br>
                    Dhar, Madhya Pradesh, 454660 <br><br>
                    <strong>Phone:</strong> +91 1234567890 <br>
                    <strong>Email:</strong> nirgovind@gmail.com<br>
                  </p>
                </div>
      
                <div class="col-lg-3 col-md-6 footer-links">
                  <h4>Links</h4>
                  <div class="row">
                    <div class="col-lg-6 col-md-12 footer-links-div">
                      <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                      </ul>
                    </div>
        
                    <div class="col-lg-6 col-md-12 footer-links-div">
                      <ul>
                        <li><a href="#">Help center</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                      </ul>
                    </div>
                  </div>
      
                </div>
      
                <div class="col-lg-3 col-md-6 footer-links">
                  <h4>Connect with us</h4>
                  <div class="social-links">
                    <p>राधे राधे!</p>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="youtube"><i class="bx bxl-youtube"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                  </div>
                </div>
      
              </div>
            </div>
          </div>
      
          <div class="container footer-bottom clearfix">
            <div class="copyright">
              &copy; Copyright <strong><span>Nirgovind</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
              Designed by nirgovind
            </div>
          </div>
        </footer><!-- End Footer -->
      
        <div id="preloader"></div>
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
      
      
        <!-- Other JS Files -->
        <script src="{% static 'external-css-js/aos/aos.js' %}"></script>
        <script src="{% static 'external-css-js/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'external-css-js/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'external-css-js/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'external-css-js/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'external-css-js/waypoints/noframework.waypoints.js' %}"></script>
        <script src="{% static 'external-css-js/php-email-form/validate.js' %}"></script>
      
        <!-- Main JS File -->
        <script src="{% static 'main.js' %}"></script>
    </div>

</body>

</html>

Home/templates/Home/contact.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Contact
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'contact/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
  <div class="title">
    Contact
  </div>
</div>

{% endblock body %}

Home/templates/Home/index.html
{% extends "Home/base.html" %}
{% load static %}
{% block title %}
NIRGOVIND
{% endblock title %}

{% block body %}


<section id="home-slideshow">
  <div class="home-slideshow-container">
    <div class="home-slide" style="display: none;">
      <img src="{% static 'img/home-image/1.jpg' %}" alt="Image 1">
      <div class="home-text">
        <h2>Slide 1</h2>
        <p>Some description for Slide 1</p>
      </div>
    </div>
    <div class="home-slide" style="display: none;">
      <img src="{% static 'img/home-image/2.jpg' %}" alt="Image 2">
      <div class="home-text">
        <h2>Slide 2</h2>
        <p>Some description for Slide 2</p>
      </div>
    </div>
    <div class="home-slide" style="display: none;">
      <img src="{% static 'img/home-image/3.jpg' %}" alt="Image 3">
      <div class="home-text">
        <h2>Slide 3</h2>
        <p>Some description for Slide 3</p>
      </div>
    </div>
    <div class="home-slide" style="display: none;">
      <img src="{% static 'img/home-image/4.jpg' %}" alt="Image 4">
      <div class="home-text">
        <h2>Slide 4</h2>
        <p>Some description for Slide 4</p>
      </div>
    </div>
  </div>
</section>

<!-- ======= Hero Section ======= -->

<section id="hero">
    <div class="mask">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="flip-up" data-aos-delay="200">
                    <h1>"If one reads Bhagavad-gita very sincerely and with all seriousness, then by the grace of the Lord the reactions of his past misdeeds will not act upon him."</h1>
                    <h2>- Lord Shiva to Paratidevi.</h2>
                </div>
            </div>
        </div>
    </div>
</section><!-- End Hero -->

<main id="main">

    <!-- ======= Notices Section ======= -->
    <section id="notices" class="notices section-bg">
      <div class="container-fluid" data-aos="fade-up">

          <div class="row">
            <div class="col-lg-6 d-flex flex-column justify-content-center align-items-stretch  order-2 order-lg-1" style="border: 5px solid white; margin-left: 10px; border-radius: 10px;">

            <div class="content">
              <h3>Notices</strong></h3>
              </p>
            </div>

            <div class="accordion-list">
              <ul>
                <li>
                  <a>Notice 1</a>
                </li>

                <li>
                  <a>Notice 2</a>
                </li>

                <li>
                  <a>Notice 3</a>
                </li>
                
                <li>
                  <a>Notice 4</a>
                </li>
              </ul>
            </div>
            <div class="footer">
              <a href="{% url 'Home:visual' %}">
                Archive
              </a>
            </div>
           </div>
          
        
      </div>

      </div>
    </section><!-- End Notices Section -->

    <!-- ======= events Section ======= -->
    <section id="events" class="events section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Events</h2>
          <p>Find the info about latest events about to be conducted in hostel and insti level. </p>
        </div>

        <div class="row">
          <div class="col-xl-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
            <div class="icon-box">
              <div class="icon"><i class="bx bxl-dribbble"></i></div>
              <h4><a href="">Lorem Ipsum</a></h4>
              <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
            </div>
          </div>

          <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="200">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-file"></i></div>
              <h4><a href="">Sed ut perspici</a></h4>
              <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
            </div>
          </div>

          <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="300">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-tachometer"></i></div>
              <h4><a href="">Magni Dolores</a></h4>
              <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
            </div>
          </div>

          <div class="col-xl-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="400">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-layer"></i></div>
              <h4><a href="">Nemo Enim</a></h4>
              <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
            </div>
          </div>

          <div class="more-info">For info about more events, click here: <a href="{% url 'Home:quotes' %}">More</a></div>

        </div>

      </div>
    </section><!-- End events Section -->    
</main><!-- End #main -->



<script>


  // main slides
  const slides = document.querySelectorAll('.home-slide');
  const texts = document.querySelectorAll('.home-text');
  let currentSlide = 0;
  
  function showSlide() {
    slides[currentSlide].classList.add('active2');
    slides[(currentSlide+1)%slides.length].style.display = 'block';
    slides[(currentSlide+1)%slides.length].classList.add('active');
    slides[currentSlide].style.display = 'none';
    slides[currentSlide].classList.remove('active');
    slides[currentSlide].classList.remove('active2');
    currentSlide = (currentSlide+1)%slides.length;
  }

  function nextSlide() {
    showSlide();
  }

  if(slides.length>0){
    slides[0].style.display = 'block';
    slides[0].classList.add('active');
  }

  if(slides.length>1){
    // Start the slideshow
    const intervalId = setInterval(nextSlide, 7000); // Change the delay (in milliseconds) as desired

    // Pause the slideshow on hover
    document.getElementById('home-slideshow').addEventListener('mouseenter', () => {
      clearInterval(intervalId);
    });

    // Resume the slideshow on mouseout
    document.getElementById('home-slideshow').addEventListener('mouseleave', () => {
      intervalId = setInterval(nextSlide, 7000); // Change the delay (in milliseconds) as desired
    });
  }
  



</script>




{% endblock body %}

Home/templates/Home/quotes.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Quotes
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'quotes/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
  <div class="title">
    Quotes
  </div>
</div>

{% endblock body %}