Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('',views.index,name='index'),
    path('visual/',views.visual,name='visual'),
    path('visual/like_slide',views.like_slide,name='like_slide'),
    path('visual/refresh_videos',views.refresh_videos,name='refresh_videos'),
    path('quotes/',views.quotes,name='quotes'),
    path('contact/',views.contact,name='contact'),
    path('login_page/',views.login_page,name='login_page'),
]

Quiz/urls.py
from django.urls import path

from . import views

app_name = "Quiz"

urlpatterns = [
    path("quiz",views.quiz_page,name='quiz'),
    path("create-new-quiz",views.createNewQuiz,name='create_new_quiz'),
    path("quiz-page-history",views.QuizHistoryAPIView.as_view(),name='quiz_page_history'),
    path("delete-quiz/",views.deleteQuiz,name='delete_quiz'),
    path("save-question",views.createQuestion,name='add_question'),
    path("preview-quiz/<str:quizId>",views.previewQuiz,name='preview_quiz'),
    path("preview-quiz-json",views.previewQuizJson,name='preview_quiz_json'),
    path("delete-question/",views.deleteQuestion,name='delete_question'),
    path("practice_quiz",views.practice_quiz,name='practice_quiz'),
    path("practice_quiz_json",views.practice_quiz_json,name='practice_quiz_json'),
    
]

nirgovind/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls',namespace="Home")),
    path('quiz/',include('Quiz.urls',namespace="Quiz")),
    path('user/',include('User.urls',namespace="User")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Quiz/models.py
from django.db import models
from django.utils import timezone
from django.db.models import UniqueConstraint
from django.contrib.auth.models import User

from nirgovind import settings

# Create your models here.

class Quiz(models.Model):
    user               = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quiz')
    quizId             = models.CharField(max_length=7, default='Aa12345', unique=True)
    quizTimeStamp      = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quizId}({self.user.username})'


class Question(models.Model):
    QUESTION_TYPES = (
        ('MCQ', 'Multiple Choice'),
        ('TF', 'True/False'),
        ('FB', 'Fill-in-the-Blank'),
        ('FMB', 'Fill-in-Multiple-Blanks'),
        ('MA', 'Multiple Answers'),
        ('DD', 'Drop-down'),
        ('MATCH', 'Matching'),
        ('NUM', 'Numerical Answer'),
        ('ESSAY', 'Essay'),
        ('UPLOAD', 'File Upload'),
    )

    quiz               = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='question')
    questionId         = models.CharField(max_length=7, default='Aa12345')
    questionType       = models.CharField(max_length=30, choices=QUESTION_TYPES, default='MCQ')
    questionText       = models.TextField(help_text="Enter Question", default="?")
    questionMarks      = models.DecimalField(max_digits=4, decimal_places=2, default=1.00)
    questionOptions    = models.CharField(max_length=4000, null=True, blank=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['quiz','questionId'], name='unique_question')
        ]
    
    def save(self, *args, **kwargs):
        if self.pk:
            try:
                self.answer.delete()
            except Answer.DoesNotExist:
                pass

        super().save(*args, **kwargs)
        self.quiz.quizTimeStamp = timezone.now()
        self.quiz.save()
        Answer.objects.create(question=self)
    
    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.quiz.quizTimeStamp = timezone.now()
        self.quiz.save()

    def __str__(self):
        return f'{self.quiz.quizId}/Question={self.questionId}({self.questionType})'

class Answer(models.Model):
    question           = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='answer')
    correctAnswer      = models.CharField(max_length=4000, null=True, blank=True)
    explaination       = models.TextField(help_text="Enter Explaination", null=True, blank=True)

    def delete(self, *args, **kwargs):
        self.question.delete()
        super().delete(*args, **kwargs)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.question.quiz.quizTimeStamp = timezone.now()
        self.question.quiz.save()

    def __str__(self):
        return f'Answer:{self.question.quiz.quizId}/Question={self.question.questionId}({self.question.questionType})'

Quiz/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.core import serializers
import json

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Quiz, Question, Answer
# Create your views here.

def quiz_page(request):
    context = {}
    return render(request,"Quiz/quiz.html",context=context)

@method_decorator(login_required, name='dispatch')
class QuizHistoryAPIView(APIView):
    def get(self, request):
        quiz_ids = [quiz.quizId for quiz in Quiz.objects.all()]
        quizzes = Quiz.objects.filter(user=request.user).order_by('-quizTimeStamp')
        quiz_data = [
            {
                'quizId': quiz.quizId,
                'updated_at': quiz.quizTimeStamp.strftime('%Y-%m-%d %H:%M:%S')
            }
            for quiz in quizzes
        ]
        question_ids = {
            quiz.quizId:[question.questionId for question in Question.objects.filter(quiz__quizId=quiz.quizId)] for quiz in quizzes
        }
        response_data = {
            'quizIds': quiz_ids,
            'questionIds':question_ids,
            'quizzes': quiz_data
        }
        return Response(response_data)


@login_required
def createNewQuiz(request):
    if request.method == 'POST':
        quizId = json.loads(request.body).get('quizId')
        Quiz.objects.create(user=request.user, quizId=quizId)
        return JsonResponse({'message': 'Quiz Created Successfully!'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

@login_required
def deleteQuiz(request):
    if request.method == 'POST':
        quizId = json.loads(request.body).get('quizId')
        Quiz.objects.get(quizId=quizId).delete()
        return JsonResponse({'message': 'Quiz Deleted Successfully!'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

@login_required
def createQuestion(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        questionId = json_data.get('oldQuestionId')
        if not questionId:
            questionId = json_data.get('questionId')

        quiz = Quiz.objects.get(quizId=json_data.get('quizId'))
        kwargs = {
            'quiz'     : quiz,
            'questionId' : questionId,
        }

        question, created = Question.objects.get_or_create(**kwargs)
        question.questionId = json_data.get('questionId')
        question.questionMarks = json_data.get('questionMarks')
        question.questionType = json_data.get('questionType')
        question.questionText = json_data.get('questionText')
        question.questionOptions = json_data.get('questionOptions')
        question.save()

        return JsonResponse({'message': 'Question saved successfully'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

@login_required
def previewQuiz(request, quizId):
    context = {
        "quizId":quizId,
        }
    return render(request,"Quiz/preview_quiz.html",context=context)

@login_required
def previewQuizJson(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        questions = Question.objects.filter(quiz__quizId=json_data.get('quizId'))
        data = serializers.serialize('json', questions)
        return JsonResponse(data, safe=False)
    else:
        return JsonResponse({'error': 'Invalid request method'})

@login_required
def deleteQuestion(request):
    if request.method == 'POST':
        quizId = json.loads(request.body).get('quizId')
        questionId = json.loads(request.body).get('questionId')
        quiz = Quiz.objects.get(quizId=quizId)
        Question.objects.get(quiz=quiz, questionId=questionId).delete()
        return JsonResponse({'message': 'Question Deleted Successfully!'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

@login_required
def practice_quiz(request):
    context = {}
    return render(request,"Quiz/practice_quiz.html",context=context)

@login_required
def practice_quiz_json(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        questions = Question.objects.filter(quiz__quizId=json_data.get('quizId')).order_by('?')#[:10]
        data = serializers.serialize('json', questions)
        return JsonResponse(data, safe=False)
    else:
        return JsonResponse({'error': 'Invalid request method'})



Quiz/templates/Quiz/practice_quiz.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Quiz
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'quiz/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
  <div class="title">
    Practice-Quiz
  </div>
  <div id="quiz-container">
    <h1>Quiz</h1>
    <form id="quiz-form">
        <div id="question-container"></div>
        <button type="submit">Submit</button>
    </form>
    <div id="score-container"></div>
  </div>

</div>


<script>
  const quizUrl = '{% url 'Quiz:practice_quiz_json' %}';
</script>

<script src="{% static 'quiz/practice_quiz.js' %}"></script>

{% endblock body %}

Quiz/templates/Quiz/preview_quiz.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Quiz-preview
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{% static 'quiz/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
  <div>
    <button id="back-button"><i class="fas fa-arrow-left"></i></button>
  </div>
  <div class="title">
    Quiz: {{quizId}}
  </div>
  <div id="quiz-container">
    <form id="quiz-form">
      <div id="question-container"></div>
    </form>
  </div>
  <div id="delete-popup" class="popup">
    <form id="delete-form">
      <h4>Confirm Delete Action</h4>
      <p> *This action will permanently delete this question!</p>
      <input type="checkbox" id="confirm-delete" required>
      <label for="confirm-delete">Yes! I am sure i want to delete.</label>
      <div>
        <button type="submit">Delete</button>
        <button type="button" id="cancel-delete">Back</button>
      </div>
    </form>
  </div>

  <div id="edit-question-popup">
    <form id="question-form">
      <label for="quiz-id" class="required-label">Quiz ID: </label>
      <input type="text" id="quiz-id" name="quiz-id" disabled>
  
      <label for="question-id" class="required-label">Question ID: </label>
      <input type="text" id="question-id" name="question-id" maxlength="7" required>
      <span id="question-id-status"><i class="fas"></i></span>
      <button onclick="resetQuestionId(event)">Reset</button>
  
      <label for="question-marks" class="required-label">Marks: </label>
      <input type="number" id="question-marks" name="question-marks" required>
      <button onclick="resetQuestionMarks(event)">Reset</button>
  
      <label for="question-type" class="required-label">Question Type: </label>
      <select id="question-type" name="question-type" onchange="toggleTextarea()" required>
        <option value="" selected>Select Question Type</option>
        <option value="MCQ">Multiple Choice</option>
        <option value="TF">True/False</option>
        <option value="FB">Fill-in-the-Blank</option>
        <option value="FMB">Fill-in-Multiple-Blanks</option>
        <option value="MA">Multiple Answers</option>
        <option value="DD">Drop-Down</option>
        <option value="MATCH">Matching</option>
        <option value="NUM">Numerical Answer</option>
        <option value="ESSAY">Essay Based</option>
        <option value="UPLOAD">File Upload</option>
      </select>
      <button onclick="resetQuestionType(event)">Reset</button>
    
      <label for="question-text" class="required-label">Question Text: </label>
      <div id="question-text-input" contenteditable="false"></div>
      <input type="hidden" id="question-text" name="question-text" required>
      <div id="question-text-message"></div>
      <button onclick="resetQuestionText(event)">Reset</button>
  
      <div id="buttons-container"></div>
    
      <div id="options-container"></div>
  
      <button type="reset" onclick="resetQuestion()">Reset</button>
      <button type="submit" id="save-button" onclick="saveForm(event)">Save</button>
      <button type="button" id="cancel-edit-question">Cancel</button>
    </form>
  </div>

</div>


<script>
  const quizUrl = '{% url 'Quiz:preview_quiz_json' %}';
  const quizId = '{{quizId}}';
  const deleteQuestionUrl = '{% url 'Quiz:delete_question' %}';
  const thisPage = `/quiz/preview-quiz/${quizId}`;
</script>

<script src="{% static 'quiz/preview_quiz.js' %}"></script>
<script src="{% static 'quiz/add_question.js' %}"></script>

{% endblock body %}

Quiz/templates/Quiz/quiz.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Quiz
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{% static 'quiz/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
  <div class="title">
    Quiz
  </div>
  <div>
    <a href="{% url 'Quiz:practice_quiz' %}"><button>Practice Quiz</button></a>
  </div>
  {% if user.is_authenticated and user.is_staff %}
  <div>
    <button id="create-quiz-btn">Create Quiz</button>
  </div>
  {% endif %}

  <div id="quiz-popup" class="popup">
    <form id="quiz-form">
      <div>
        <label for="quiz-id-input">Enter Quiz ID: <p>(*max length: 7)</p></label>
        <input type="text" id="quiz-id-input" maxlength="7" required>
        <span id="quiz-id-status"><i class="fas"></i></span>
      </div>
      <div>
        <button type="submit">Submit</button>
        <button type="button" id="cancel-btn">Cancel</button>
      </div>
    </form>
  </div>
  <div id="delete-popup" class="popup">
    <form id="delete-form">
      <h4>Confirm Delete Action</h4>
      <p> *This action will permanently delete all the questions inside the quiz!</p>
      <input type="checkbox" id="confirm-delete" required>
      <label for="confirm-delete">Yes! I am sure i want to delete.</label>
      <div>
        <button type="submit">Delete</button>
        <button type="button" id="cancel-delete">Back</button>
      </div>
    </form>
  </div>
  <div id="add-question-popup">
    <form id="question-form">
      <label for="quiz-id" class="required-label">Quiz ID: </label>
      <input type="text" id="quiz-id" name="quiz-id" disabled>
  
      <label for="question-id" class="required-label">Question ID: </label>
      <input type="text" id="question-id" name="question-id" maxlength="7" required>
      <span id="question-id-status"><i class="fas"></i></span>
      <button onclick="resetQuestionId(event)">Reset</button>
  
      <label for="question-marks" class="required-label">Marks: </label>
      <input type="number" id="question-marks" name="question-marks" required>
      <button onclick="resetQuestionMarks(event)">Reset</button>
  
      <label for="question-type" class="required-label">Question Type: </label>
      <select id="question-type" name="question-type" onchange="toggleTextarea()" required>
        <option value="" selected>Select Question Type</option>
        <option value="MCQ">Multiple Choice</option>
        <option value="TF">True/False</option>
        <option value="FB">Fill-in-the-Blank</option>
        <option value="FMB">Fill-in-Multiple-Blanks</option>
        <option value="MA">Multiple Answers</option>
        <option value="DD">Drop-Down</option>
        <option value="MATCH">Matching</option>
        <option value="NUM">Numerical Answer</option>
        <option value="ESSAY">Essay Based</option>
        <option value="UPLOAD">File Upload</option>
      </select>
      <button onclick="resetQuestionType(event)">Reset</button>
    
      <label for="question-text" class="required-label">Question Text: </label>
      <div id="question-text-input" contenteditable="false"></div>
      <input type="hidden" id="question-text" name="question-text" required>
      <div id="question-text-message"></div>
      <button onclick="resetQuestionText(event)">Reset</button>
  
      <div id="buttons-container"></div>
    
      <div id="options-container"></div>
  
      <button type="reset" onclick="resetQuestion()">Reset</button>
      <button type="submit" id="save-button" onclick="saveForm(event)">Save</button>
      <button type="submit" id="save&add-button" onclick="saveAddForm(event)">Save & Add Another</button>
      <button type="button" id="cancel-add-question">Cancel</button>
    </form>
  </div>

  <div id="quiz-list"></div>
</div>

<script>
  const quizHistoryUrl = '{% url 'Quiz:quiz_page_history' %}';
  const createNewQuizUrl = '{% url 'Quiz:create_new_quiz' %}';
  const deleteQuizUrl = '{% url 'Quiz:delete_quiz' %}';
  const thisPage = '{% url 'Quiz:quiz' %}';
</script>

<script src="{% static 'quiz/quiz.js' %}"></script>
<script src="{% static 'quiz/add_question.js' %}"></script>

{% endblock body %}