Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('',views.index,name='index'),
    path('visual/',views.visual,name='visual'),
    path('visual/like_slide',views.like_slide,name='like_slide'),
    path('visual/refresh_videos',views.refresh_videos,name='refresh_videos'),
    path('quotes/',views.quotes,name='quotes'),
    path('contact/',views.contact,name='contact'),
    path('login_page/',views.login_page,name='login_page'),
]

User/urls.py
from django.urls import path

from . import views

app_name = "User"

urlpatterns = [
    path("logout",views.logout_user,name='logout'),
    path("login",views.login_user,name='login'),
    path("otp_verification",views.send_otp,name='send_otp'),
    path("verify_otp",views.verify_otp,name='verify_otp'),
    path("reset_password/",views.password_reset,name='reset_password'),
    path("signup",views.signup_user,name='signup'),
    path("profile/<username>",views.view_profile,name='profile'),
    path("edit_profile",views.edit_profile,name='edit_profile'),
    path("edit_password",views.change_password,name='change_password'),
    
]

nirgovind/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls',namespace="Home")),
    path('quiz/',include('Quiz.urls',namespace="Quiz")),
    path('user/',include('User.urls',namespace="User")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

User/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator

from nirgovind import settings
# Create your models here.

class UserProfile(models.Model):

    def profile_pic_path(instance,filename):
        ext = filename.split('.')[-1]
        new_name = f'{instance.user.username}.{ext}'
        path = os.path.join(settings.MEDIA_ROOT,'profile_pic',new_name)
        return path

    # custom validator
    def only_int(value: str): 
        if value.isdigit()==False:
            raise ValidationError('Not valid phone number')
    
    # model fields
    user                = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user_profile')
    phone               = models.CharField(max_length=10,validators=[only_int,MinLengthValidator(10)],null=True,blank=True)
    about               = models.TextField(null=True,blank=True)
    profile_pic         = models.ImageField(upload_to=profile_pic_path,null=True,blank=True)
    location            = models.CharField(max_length=100, blank=True)
    website             = models.URLField(blank=True)
    instagram_link      = models.URLField(blank=True)
    facebook_link       = models.URLField(blank=True)
    linkedin_link       = models.URLField(blank=True)
    twitter_link        = models.URLField(blank=True)

    def __str__(self):
        return f'{self.user.username}'
    
    class Meta:
        verbose_name_plural = 'User Profiles'
        ordering = ['user']

User/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password

from .models import UserProfile
from .widgets import ImageWidget

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username/Email'
        for f in self.visible_fields():
            f.field.widget.attrs['class'] = 'input1'
    
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        # Check if the username is an email
        try:
            user = User.objects.get(email=username)
        except User.DoesNotExist:
            user = None

        # Authenticate the user using username or email
        self.user_cache = authenticate(self.request, username=username, password=password)
        
        if self.user_cache is None:
            if user is not None:
                self.user_cache = authenticate(self.request, username=user.username, password=password)

        if self.user_cache is None:
            raise self.get_invalid_login_error()
        
        self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data
    

class SignupForm(UserCreationForm):
    
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)
    profile_pic = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'profile_pic', 'email', 'password1', 'password2')
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.visible_fields():
            f.field.widget.attrs['class'] = 'input1'

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        # Check if username is already taken
        if User.objects.filter(username=username).exists():
            self.add_error('username', 'This username is already taken.')

        # Check if email is already registered
        if User.objects.filter(email=email).exists():
            self.add_error('email', 'This email is already registered.')

        return cleaned_data
    

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for f in self.visible_fields():
            f.field.widget.attrs['class'] = 'input1'
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        # Check if username is already taken
        if self.instance.username!=username and User.objects.filter(username=username).exists():
            self.add_error('username', 'This username is already taken.')

        # Check if email is already registered
        if self.instance.email!=email and User.objects.filter(email=email).exists():
            self.add_error('email', 'This email is already registered.')

        return cleaned_data



class UserProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('phone','about','profile_pic','location', 'website', 'instagram_link', 'facebook_link', 'linkedin_link', 'twitter_link')
        #widgets = {
        #    'profile_pic': ImageWidget,
        #}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for f in self.visible_fields():
            f.field.widget.attrs['class'] = 'input1'


User/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import random
from django.core.mail import send_mail
from urllib.parse import urlencode

from .models import UserProfile
from .forms import UserUpdateForm,UserProfileUpdateForm,LoginForm,SignupForm
# Create your views here.

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("Home:index"))


def login_user(request):

    if request.method !="POST":
        #display a blank form
        form = LoginForm(request)
    
    else:
        form = LoginForm(request,data = request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return HttpResponseRedirect(reverse("Home:index"))

    context = {"form":form}

    return render(request,"User/login.html",context=context)

def send_otp(request):

    message = ""
    if request.method != 'POST':
        form = PasswordResetForm()
    else:
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                
                # Generate OTP
                otp = random.randint(100000, 999999)
                
                # Send OTP to user's email
                send_mail(
                    'OTP Verification',
                    f'Your OTP is: {otp}',
                    'noreply@example.com',
                    [email],
                    fail_silently=False,
                )
                
                # Store the OTP in session for verification
                request.session['otp'] = otp
                request.session['email'] = email
                
                return HttpResponseRedirect(reverse("User:verify_otp"))
            else:
                message = "This email is not registered."

    context = {"form":form,
               "message":message,}

    return render(request,"User/send_otp.html",context=context)

def verify_otp(request):
    if request.method != 'POST':
        error_message = ''
    
    else:
        entered_otp = request.POST.get('otp')
        stored_otp = request.session.get('otp')
        email = request.session.get('email')
        
        if entered_otp == str(stored_otp):
            # OTP verification successful
            # Clear the OTP and email from the session
            del request.session['otp']
            del request.session['email']
            
            query_params = urlencode({'email': email})
            redirect_url = reverse('User:reset_password') + '?' + query_params
            # Redirect to the password reset page on successful verification
            return HttpResponseRedirect(redirect_url)
        else:
            # OTP verification failed
            # Handle the error or display an error message
            error_message = 'Invalid OTP. Please try again.'
        
    context = {'error_message': error_message,}
    return render(request, "User/verify_otp.html", context)

def password_reset(request):

    if request.method != 'POST':
        email = request.GET.get('email')
        user = User.objects.get(email=email)
        form = SetPasswordForm(user)

    else:
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            # Save the new password
            form.save()
            return HttpResponseRedirect(reverse("User:login"))

    context = {
        'form': form,
        'email': email,
    }
    return render(request, "User/reset_password.html", context)

def signup_user(request):

    if request.method !="POST":
        #display a blank form
        form = SignupForm()
    
    else:
        form = SignupForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()
            profile_pic = form.cleaned_data['profile_pic'] 
            profile = UserProfile(user=user, profile_pic=profile_pic)
            profile.save()
            return HttpResponseRedirect(reverse("User:login"))

    context = {"form":form,}

    return render(request,"User/signup.html",context=context)

def view_profile(request,username):

    user = User.objects.get(username=username)

    context = {"user":user,}
    return render(request,"User/profile.html",context=context)

@login_required
def edit_profile(request):

    if request.method != "POST":
        # display blank form
        form1 = UserUpdateForm(instance=request.user)
        form2 = UserProfileUpdateForm(instance=request.user.user_profile)
    else:
        # process form data
        form1 = UserUpdateForm(request.POST, instance=request.user)
        form2 = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user.user_profile)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()

            return HttpResponseRedirect(reverse("User:profile",kwargs={"username": request.user.username}))

    context = {
        "form1":form1,
        "form2":form2,
        "username":request.user.username,
    }
    return render(request,"User/edit_profile.html",context=context)

@login_required
def change_password(request):
    if request.method != "POST":
        # display blank form
        form = PasswordChangeForm(request.user)
    else:
        # process form data
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("User:login"))

    context = {"form":form}
    return render(request,"User/change_password.html",context=context)

User/templates/User/change_password.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Change_Password
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}


{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <form action="{% url 'User:change_password' %}" method="post">
        <h2>Change Your Password</h2>
        {% csrf_token %}
        {{form}}
        <input type="checkbox" id="showPassword">
        <label for="showPassword">Show Password</label>
        <div class="submit-btn">
            <button name="submit" type="submit">Save</button>
        </div>
        </form>
        <a href="{% url 'User:profile' user.username %}">
            <button type="submit">Cancel</button>
        </a>
    </div>
</div>

<script>
    // Toggle password visibility when the checkbox is clicked
    document.getElementById("showPassword").addEventListener("change", function() {
      var passwordInput = document.getElementById("id_new_password1");
      if (passwordInput.type === "password") {
        passwordInput.type = "text";
      } else {
        passwordInput.type = "password";
      }
    });
</script>
  

{% endblock %}

User/templates/User/edit_profile.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Edit_Profile
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'form/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <h2>Edit Your Profile</h2>
        <form method="post" enctype="multipart/form-data" action="{% url 'User:edit_profile' %}">
            {% csrf_token %}
            {{ form1 }}
            {{ form2 }}
            <div class="submit-btn">
                <button name="submit" type="submit">Save</button>
            </div>
        </form>
        <a href="{% url 'User:profile' username %}">
            <button type="submit">Cancel</button>
        </a>
    </div>
</div>
{% endblock body %}

User/templates/User/login.html
{% extends "Home/base.html" %}
{% load static %}
{% block title %}
NIRGOVIND-Login
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <form action="{% url 'User:login' %}" method="post">
        <h2>Login</h2>
        
        {% csrf_token %}
        {{ form.as_p }}
        <!--<div class="input-field">
            <label for="username">Username or Email:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div class="input-field">
            <div class="toggle-password">
            <p class="toggle-password-text">Show</p>
            </div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>-->
        <input type="checkbox" id="showPassword">
        <label for="showPassword">Show Password</label>
        <div class="submit-btn">
            <button name="submit" type="submit">Login</button>
        </div>
        </form>
        <div>
            <a href="{% url 'Home:index' %}">
                <button type="submit">Cancel</button>
            </a>
        </div>
        <a href="{% url 'User:send_otp' %}">Forgot Password?</a>
        <div class="sign-up">
            <a href="{% url 'User:signup' %}">
                <button type="submit">Sign up</button>
            </a>
        </div>
    </div>
</div>

<script>
    // Toggle password visibility when the checkbox is clicked
    document.getElementById("showPassword").addEventListener("change", function() {
      var passwordInput = document.getElementById("id_password");
      if (passwordInput.type === "password") {
        passwordInput.type = "text";
      } else {
        passwordInput.type = "password";
      }
    });
</script>

{% endblock body %}

User/templates/User/profile.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Profile
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'profile/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <h2>Profile</h2>

        <img {% if user.user_profile.profile_pic %} src="{{ user.user_profile.profile_pic.url }}" {% endif %} alt="No Profile Picture" width="200" height="200">
        
        <h2>{{user.first_name}} {{user.last_name}} ({{ user.username }})</h2>

        <p><a href="{% url 'User:edit_profile' %}">Edit profile</a></p>
        <p><a href="{% url 'User:change_password' %}">Change Password</a></p>

        <p>Email : {{user.email}} </p>
        <p>Phone Number : {{user.user_profile.phone}} </p>
        <p>About : {{user.user_profile.about}}</p>
        <p>location: {{ user.user_profile.location }}</p>
        <p>Website: <a href="{{ user.user_profile.website }}" target="_blank">{{ user.user_profile.website }}</a></p>
        <p>Instagram: <a href="{{ user.user_profile.instagram_link }}" target="_blank">{{ user.user_profile.instagram_link }}</a></p>
        <p>Facebook: <a href="{{ user.user_profile.facebook_link }}" target="_blank">{{ user.user_profile.facebook_link }}</a></p>
        <p>Twitter: <a href="{{ user.user_profile.twitter_link }}" target="_blank">{{ user.user_profile.twitter_link }}</a></p>
        <p>LinkedIn: <a href="{{ user.user_profile.linkedin_link }}" target="_blank">{{ user.user_profile.linkedin_link }}</a></p>
    </div>
</div>

{% endblock body %}

User/templates/User/reset_password.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Reset_password
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}


{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
      <p>Email: {{ email }} </p>
        <form method="POST" action="{% url 'User:reset_password' %}">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="email" value="{{ email }}">
            <!--<div>
              <label for="new_password1">New Password:</label>
              <input type="password" id="new_password1" name="new_password1">
            </div>
            
            <div>
              <label for="new_password2">Confirm New Password:</label>
              <input type="password" id="new_password2" name="new_password2">
            </div>-->
            <input type="checkbox" id="showPassword">
            <label for="showPassword">Show Password</label>
            <button type="submit">Reset Password</button>
          </form>
    </div>
</div>

<script>
  // Toggle password visibility when the checkbox is clicked
  document.getElementById("showPassword").addEventListener("change", function() {
    var passwordInput = document.getElementById("id_new_password1");
    if (passwordInput.type === "password") {
      passwordInput.type = "text";
    } else {
      passwordInput.type = "password";
    }
  });
</script>

{% endblock %}

User/templates/User/send_otp.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Send_otp
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}


{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <form method="POST">
            {% csrf_token %}
            
            {{ form.email.label_tag }}
            {{ form.email }}
            <p>{{ message }}</p>
            <button type="submit">Send OTP</button>
          </form>
    </div>
</div>

{% endblock %}

User/templates/User/signup.html
{% extends "Home/base.html" %}
{% load static %}
{% block title %}
NIRGOVIND-Signup
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}

{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <form action="{% url 'User:signup' %}" method="post" enctype="multipart/form-data">
        <h2>Signup</h2>
        {% csrf_token %}
        
        <div>
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
          
        <div>
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
        </div>
          
        <div>
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
        </div>
          
        <div>
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
          
        <div>
            {{ form.password1.label_tag }}
            {{ form.password1 }}
            <input type="checkbox" id="showPassword">
            <label for="showPassword">Show Password</label>
        </div>
          
        <div>
            {{ form.password2.label_tag }}
            {{ form.password2 }}
        </div>
          
        <div>
            {{ form.profile_pic.label_tag }}
            {{ form.profile_pic }}
        </div>
        <!--<div class="input-field">
            <label for="username">Username or Email:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div class="input-field">
            <div class="toggle-password">
            <p class="toggle-password-text">Show</p>
            </div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div class="submit-btn">
            <button name="submit" type="submit">Login</button>
            <a href="{% url 'Home:index' %}">
                <button type="submit">Cancel</button>
            </a>
        </div>
        <a href="#">Forgot Password?</a>-->

        <div class="sign-up">
            <button type="submit">Sign up</button>
        </div>
        </form>
    </div>
</div>

<script>
    // Toggle password visibility when the checkbox is clicked
    document.getElementById("showPassword").addEventListener("change", function() {
      var passwordInput = document.getElementById("id_password1");
      if (passwordInput.type === "password") {
        passwordInput.type = "text";
      } else {
        passwordInput.type = "password";
      }
    });
  </script>

{% endblock body %}

User/templates/User/verify_otp.html
{% extends 'Home/base.html' %}
{% load static %}
{% block title %}
NIRGOVIND-Verify_otp
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'login/style.css' %}">
{% endblock css %}


{% block body %}

<!-- ======= Main ======= -->
<div class="main">
    <div class="maincontainer">
        <form method="POST">
            {% csrf_token %}
            
            {% if error_message %}
            <p>{{ error_message }}</p>
            {% endif %}
            
            <label for="otp">Enter OTP:</label>
            <input type="text" id="otp" name="otp">
            
            <button type="submit">Verify OTP</button>
          </form>
    </div>
</div>

{% endblock %}